# environment variables for any dev environment
version: '3'

services:
  # service name has to be environment-unique, else one startup will shutdown others
  lsb2-images:
    labels:
      lsb2.template.description: "Images Server for local environment"
      lsb2.version: $TAG
    image: "jghamburg/lsb2-images:$TAG"
    build:
      context: ../..
      dockerfile: ./docker/Dockerfile
      args:
        JAR_FILE: ./build/libs/lsb2-images.jar
    ports:
      - "8200:8080" # web port
    environment:
      PROFILE: "default"
      PORT: 8080
#      DEBUG_PORT: "48200"
#      JAVA_REMOTE_DEBUGGING: "true"
#    volumes:
#      - ../../upload-dir:/app/upload-dir
