# environment variables for any dev environment
version: '3'

services:
  # service name has to be environment-unique, else one startup will shutdown others
  local-images-server:
    labels:
      de.otto.template.description: "Images Server for local environment"
      de.otto.drop.brandshopupdater.version: "local"
    image: "images-server:local"
    build:
      context: ../..
      dockerfile: ./docker/Dockerfile
    ports:
      - "8200:8200" # web port
      - "48200:48200" # debug port
    environment:
      PROFILE: "local"
      JAVA_REMOTE_DEBUGGING: "true"
      DEBUG_PORT: "48200"
    networks:
      - learn-ms-network

networks:
  learn-ms-network:
    external: true


