# environment variables for any dev environment
version: '3'

services:
  # service name has to be environment-unique, else one startup will shutdown others
  local-images-server:
    labels:
      lsb2.template.description: "Images Server for local environment"
      lsb2.version: "local"
    image: "images-server:local"
    build:
      context: ../..
      dockerfile: ./docker/Dockerfile
      args:
        JAR_FILE: ./build/libs/lsb2-images.jar
    ports:
      - "8200:8200" # web port
      - "48200:48200" # debug port
    environment:
      PROFILE: "local"
      JAVA_REMOTE_DEBUGGING: "true"
      DEBUG_PORT: "48200"
    volumes:
      - ../../upload-dir:/app/upload-dir
    networks:
      - learn-ms-network

networks:
  learn-ms-network:
    external: true


